### ISSUE TITLE
npm install failing on macOS

### ISSUE THREAD

**Issue by cclauss** [richierockskool/homebridge-inkbird-wifi-gateway#18]
A continuation of nodejs/node-gyp#2852

@richierockskool Please try the following commands on your Mac and paste the results here...
1. `ls -hal ~ | grep node_modules`
2. `ls -hal ~/.npm-packages/lib | grep node_modules`
3. `ls -hal ~/.npm-packages/lib/node_modules | grep inkbird`
4. `ls -hal ~/.npm-packages/lib/node_modules | grep rename`

It is strange that on my Mac, my `node_modules` are in `~` and on yours they are in `~/.npm-packages/lib`

**Comment by richierockskool** [comment]
> On Jun 6, 2023, at 1:31 AM, Christian Clauss ***@***.***> wrote:
> 
> 
> A continuation of nodejs/node-gyp#2852 <https://github.com/nodejs/node-gyp/issues/2852>
> @richierockskool <https://github.com/richierockskool> Please try the following commands on your Mac and paste the results here...
> 
> ls -hal ~ | grep node_modules
drwxrwxrwx   81 richjagger  staff   2.5K May 25 10:17 node_modules
> ls -hal ~/.npm-packages/lib | grep node_modules
drwxr-xr-x  9 richjagger  admin   288B May 24 22:21 node_modules
> ls -hal ~/.npm-packages/lib/node_modules | grep inkbird
drwxrwxrwx   2 richjagger  admin    64B May 21 12:40 .homebridge-inkbird-wifi-gateway-3htFxu5w
lrwxr-xr-x   1 richjagger  admin    57B May 21 12:09 homebridge-inkbird-wifi-gateway -> ../../../Documents/GitHub/homebridge-inkbird-wifi-gateway
> ls -hal ~/.npm-packages/lib/node_modules | grep rename
***@***.*** homebridge-inkbird-wifi-gateway % ls -hal ~/.npm-packages/lib/node_modules | grep rename (this one does not work)

**Comment by cclauss** [comment]
I think this is a problem...  The code is trying to rename a link to a directory in a different part of the disk.
```
lrwxr-xr-x   1 richjagger  admin    57B May 21 12:09 homebridge-inkbird-wifi-gateway -> ../../../Documents/GitHub/homebridge-inkbird-wifi-gateway
```
Perhaps try `cd ../../../Documents/GitHub/homebridge-inkbird-wifi-gateway` and try running your install again.

**Comment by richierockskool** [comment]
I get the same result…

***@***.*** homebridge-inkbird-wifi-gateway % cd ../../../Documents/GitHub/homebridge-inkbird-wifi-gateway
***@***.*** homebridge-inkbird-wifi-gateway % npm install -g homebridge-inkbird-wifi-gateway
npm ERR! code EISDIR
npm ERR! syscall rename
npm ERR! path /Users/richjagger/.npm-packages/lib/node_modules/homebridge-inkbird-wifi-gateway
npm ERR! dest /Users/richjagger/.npm-packages/lib/node_modules/.homebridge-inkbird-wifi-gateway-3htFxu5w
npm ERR! errno -21
npm ERR! EISDIR: illegal operation on a directory, rename '/Users/richjagger/.npm-packages/lib/node_modules/homebridge-inkbird-wifi-gateway' -> '/Users/richjagger/.npm-packages/lib/node_modules/.homebridge-inkbird-wifi-gateway-3htFxu5w'

*** something else I noticed **

My Terminal keeps doing this?? and switching back a forth…Is this an issue?

***@***.*** homebridge-inkbird-wifi-gateway


***@***.*** homebridge-inkbird-wifi-gateway

The first drops the “R” in Rita

**Comment by cclauss** [comment]
Please review and merge #17 so we can see if we can replicate your issue there.

**Comment by richierockskool** [comment]
Build 16x is now failing?


[13_Complete job.txt](https://github.com/richierockskool/homebridge-inkbird-wifi-gateway/files/13796698/13_Complete.job.txt)
[1_Set up job.txt](https://github.com/richierockskool/homebridge-inkbird-wifi-gateway/files/13796699/1_Set.up.job.txt)
[2_Run actionscheckout@v3.txt](https://github.com/richierockskool/homebridge-inkbird-wifi-gateway/files/13796700/2_Run.actionscheckout%40v3.txt)
[3_Use Node.js 16.x.txt](https://github.com/richierockskool/homebridge-inkbird-wifi-gateway/files/13796701/3_Use.Node.js.16.x.txt)
[4_Install dependencies.txt](https://github.com/richierockskool/homebridge-inkbird-wifi-gateway/files/13796702/4_Install.dependencies.txt)
2023-12-30T00:36:00.3224990Z ##[group]Run npm install
2023-12-30T00:36:00.3225550Z [36;1mnpm install[0m
2023-12-30T00:36:00.3365530Z shell: /bin/bash -e {0}
2023-12-30T00:36:00.3366030Z ##[endgroup]
2023-12-30T00:36:01.0376710Z npm WARN EBADENGINE Unsupported engine {
2023-12-30T00:36:01.0378680Z npm WARN EBADENGINE   package: 'homebridge-inkbird-wifi-gateway@1.2.1',
2023-12-30T00:36:01.0380070Z npm WARN EBADENGINE   required: { node: '^18.17.0 || >=20.5.0', homebridge: '>=1.7' },
2023-12-30T00:36:01.0381770Z npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
2023-12-30T00:36:01.0382590Z npm WARN EBADENGINE }
2023-12-30T00:36:01.0390620Z npm WARN EBADENGINE Unsupported engine {
2023-12-30T00:36:01.0391590Z npm WARN EBADENGINE   package: 'homebridge@1.7.0',
2023-12-30T00:36:01.0392580Z npm WARN EBADENGINE   required: { node: '^18.15.0 || ^20.7.0' },
2023-12-30T00:36:01.0394040Z npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
2023-12-30T00:36:01.0394950Z npm WARN EBADENGINE }
2023-12-30T00:36:01.0398250Z npm WARN EBADENGINE Unsupported engine {
2023-12-30T00:36:01.0399510Z npm WARN EBADENGINE   package: 'npm@10.2.5',
2023-12-30T00:36:01.0400520Z npm WARN EBADENGINE   required: { node: '^18.17.0 || >=20.5.0' },
2023-12-30T00:36:01.0401620Z npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
2023-12-30T00:36:01.0402840Z npm WARN EBADENGINE }
2023-12-30T00:36:12.3665910Z npm ERR! code 1
2023-12-30T00:36:12.3679110Z npm ERR! path /Users/runner/work/homebridge-inkbird-wifi-gateway/homebridge-inkbird-wifi-gateway/node_modules/@abandonware/noble
2023-12-30T00:36:12.3690770Z npm ERR! command failed
2023-12-30T00:36:12.3692460Z npm ERR! command sh -c -- node-gyp-build
2023-12-30T00:36:12.3694230Z npm ERR! gyp info it worked if it ends with ok
2023-12-30T00:36:12.3700000Z npm ERR! gyp info using node-gyp@9.1.0
2023-12-30T00:36:12.3701610Z npm ERR! gyp info using node@16.20.2 | darwin | x64
2023-12-30T00:36:12.3703590Z npm ERR! gyp info find Python using Python version 3.12.1 found at "/usr/local/bin/python3"
2023-12-30T00:36:12.3705900Z npm ERR! gyp http GET https://nodejs.org/download/release/v16.20.2/node-v16.20.2-headers.tar.gz
2023-12-30T00:36:12.3719120Z npm ERR! gyp http 200 https://nodejs.org/download/release/v16.20.2/node-v16.20.2-headers.tar.gz
2023-12-30T00:36:12.3721830Z npm ERR! gyp http GET https://nodejs.org/download/release/v16.20.2/SHASUMS256.txt
2023-12-30T00:36:12.3751410Z npm ERR! gyp http 200 https://nodejs.org/download/release/v16.20.2/SHASUMS256.txt
2023-12-30T00:36:12.3798220Z npm ERR! gyp info spawn /usr/local/bin/python3
2023-12-30T00:36:12.3799820Z npm ERR! gyp info spawn args [
2023-12-30T00:36:12.3802810Z npm ERR! gyp info spawn args   '/Users/runner/hostedtoolcache/node/16.20.2/x64/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
2023-12-30T00:36:12.3805450Z npm ERR! gyp info spawn args   'binding.gyp',
2023-12-30T00:36:12.3807000Z npm ERR! gyp info spawn args   '-f',
2023-12-30T00:36:12.3808690Z npm ERR! gyp info spawn args   'make',
2023-12-30T00:36:12.3810170Z npm ERR! gyp info spawn args   '-I',
2023-12-30T00:36:12.3812630Z npm ERR! gyp info spawn args   '/Users/runner/work/homebridge-inkbird-wifi-gateway/homebridge-inkbird-wifi-gateway/node_modules/@abandonware/noble/build/config.gypi',
2023-12-30T00:36:12.3815410Z npm ERR! gyp info spawn args   '-I',
2023-12-30T00:36:12.3817150Z npm ERR! gyp info spawn args   '/Users/runner/hostedtoolcache/node/16.20.2/x64/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
2023-12-30T00:36:12.3819200Z npm ERR! gyp info spawn args   '-I',
2023-12-30T00:36:12.3820530Z npm ERR! gyp info spawn args   '/Users/runner/Library/Caches/node-gyp/16.20.2/include/node/common.gypi',
2023-12-30T00:36:12.3824840Z npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
2023-12-30T00:36:12.3826030Z npm ERR! gyp info spawn args   '-Dvisibility=default',
2023-12-30T00:36:12.3827380Z npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/runner/Library/Caches/node-gyp/16.20.2',
2023-12-30T00:36:12.3830860Z npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/runner/hostedtoolcache/node/16.20.2/x64/lib/node_modules/npm/node_modules/node-gyp',
2023-12-30T00:36:12.3835280Z npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/runner/Library/Caches/node-gyp/16.20.2/<(target_arch)/node.lib',
2023-12-30T00:36:12.3839020Z npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/runner/work/homebridge-inkbird-wifi-gateway/homebridge-inkbird-wifi-gateway/node_modules/@abandonware/noble',
2023-12-30T00:36:12.3841370Z npm ERR! gyp info spawn args   '-Dnode_engine=v8',
2023-12-30T00:36:12.3842900Z npm ERR! gyp info spawn args   '--depth=.',
2023-12-30T00:36:12.3843930Z npm ERR! gyp info spawn args   '--no-parallel',
2023-12-30T00:36:12.3844990Z npm ERR! gyp info spawn args   '--generator-output',
2023-12-30T00:36:12.3845860Z npm ERR! gyp info spawn args   'build',
2023-12-30T00:36:12.3846720Z npm ERR! gyp info spawn args   '-Goutput_dir=.'
2023-12-30T00:36:12.3873460Z npm ERR! gyp info spawn args ]
2023-12-30T00:36:12.3874300Z npm ERR! Traceback (most recent call last):
2023-12-30T00:36:12.3876600Z npm ERR!   File "/Users/runner/hostedtoolcache/node/16.20.2/x64/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
2023-12-30T00:36:12.3878220Z npm ERR!     import gyp  # noqa: E402
2023-12-30T00:36:12.3878840Z npm ERR!     ^^^^^^^^^^
2023-12-30T00:36:12.3880670Z npm ERR!   File "/Users/runner/hostedtoolcache/node/16.20.2/x64/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
2023-12-30T00:36:12.3882310Z npm ERR!     import gyp.input
2023-12-30T00:36:12.3884480Z npm ERR!   File "/Users/runner/hostedtoolcache/node/16.20.2/x64/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
2023-12-30T00:36:12.3886370Z npm ERR!     from distutils.version import StrictVersion
2023-12-30T00:36:12.3887470Z npm ERR! ModuleNotFoundError: No module named 'distutils'
2023-12-30T00:36:12.3888830Z npm ERR! gyp ERR! configure error 
2023-12-30T00:36:12.3889710Z npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
2023-12-30T00:36:12.3892210Z npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/Users/runner/hostedtoolcache/node/16.20.2/x64/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:284:16)
2023-12-30T00:36:12.3894300Z npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
2023-12-30T00:36:12.3895840Z npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
2023-12-30T00:36:12.3897100Z npm ERR! gyp ERR! System Darwin 21.6.0
2023-12-30T00:36:12.3899680Z npm ERR! gyp ERR! command "/Users/runner/hostedtoolcache/node/16.20.2/x64/bin/node" "/Users/runner/hostedtoolcache/node/16.20.2/x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2023-12-30T00:36:12.3902970Z npm ERR! gyp ERR! cwd /Users/runner/work/homebridge-inkbird-wifi-gateway/homebridge-inkbird-wifi-gateway/node_modules/@abandonware/noble
2023-12-30T00:36:12.3904630Z npm ERR! gyp ERR! node -v v16.20.2
2023-12-30T00:36:12.3905350Z npm ERR! gyp ERR! node-gyp -v v9.1.0
2023-12-30T00:36:12.3905990Z npm ERR! gyp ERR! not ok
2023-12-30T00:36:12.3906290Z 
2023-12-30T00:36:12.3906660Z npm ERR! A complete log of this run can be found in:
2023-12-30T00:36:12.3907770Z npm ERR!     /Users/runner/.npm/_logs/2023-12-30T00_36_00_635Z-debug-0.log
2023-12-30T00:36:12.3927290Z ##[error]Process completed with exit code 1.

[12_Post Run actionscheckout@v3.txt](https://github.com/richierockskool/homebridge-inkbird-wifi-gateway/files/13796703/12_Post.Run.actionscheckout%40v3.txt)
