### ISSUE TITLE
Problems getting Homebridge recognize the plugin

### ISSUE THREAD

**Issue by richierockskool** [richierockskool/homebridge-inkbird-wifi-gateway#2]
This is a Homebridge plugin to hook into the Inkbird Gateway that I am trying to get working,
I keep get this message...No plugin was found for the platform "homebridge-inkbird-wifi-gateway" in your config.json. Please make sure the corresponding plugin is installed correctly.
Here is my config.json
"platform":"HomebridgeInkbirdWifiGateway",
            "name": "homebridge-inkbird-wifi-gateway",
            "model": "IBS-M1S",
            "mac_address": "e8:db:84:b6:9c:e6",
            "ip": "99.228.220.201",
            "update_interval": 600,
            "storage": "filesystem",
            "loglevel": 3

**Comment by richierockskool** [comment]
getting these errors:
Error loading the platform "HomebridgeInkbirdWifiGateway" requested in your config.json at position 5 - this is likely an issue with the "homebridge-inkbird-wifi-gateway" plugin.

Error: The requested platform 'HomebridgeInkbirdWifiGateway' was not registered by the plugin 'homebridge-inkbird-wifi-gateway'.
    at Plugin.getPlatformConstructor (/usr/local/lib/node_modules/homebridge/src/plugin.ts:154:13)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:432:30
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:400:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:176:29)

**Comment by richierockskool** [comment]
ERROR LOADING PLUGIN homebridge-inkbird-wifi-gateway:
[8/6/2022, 1:19:11 PM] /Users/richjagger/Documents/GitHub/Hombridge-Inkbird-Wifi-Gateway/dist/index.js:2
import { PLATFORM_NAME } from "./settings";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/src/plugin.ts:227:93)
    at PluginManager.initializeInstalledPlugins (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:141:22)

**Comment by richierockskool** [comment]
Still getting these errors,

No plugin was found for the platform "HomebridgeInkbirdWifiGateway" in your config.json. Please make sure the corresponding plugin is installed correctly.


ERROR LOADING PLUGIN homebridge-inkbird-wifi-gateway:
[8/26/2022, 8:39:33 AM] Error: Cannot find module '/usr/local/lib/node_modules/homebridge-inkbird-gateway/src/index.js' imported from /usr/local/lib/node_modules/homebridge/lib/plugin.js
    at new NodeError (node:internal/errors:387:5)
    at finalizeResolution (node:internal/modules/esm/resolve:429:11)
    at moduleResolve (node:internal/modules/esm/resolve:1006:10)
    at defaultResolve (node:internal/modules/esm/resolve:1214:11)
    at nextResolve (node:internal/modules/esm/loader:165:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:844:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:431:18)
    at ESMLoader.import (node:internal/modules/esm/loader:528:22)
    at importModuleDynamically (node:internal/modules/cjs/loader:1065:29)
    at importModuleDynamicallyWrapper (node:internal/vm/module:438:21)

And these warnings

[8/26/2022, 8:39:33 AM] Warning: skipping plugin found at '/usr/local/lib/node_modules/homebridge-inkbird-wifi-gateway' since we already loaded the same plugin from '/usr/local/lib/node_modules/homebridge-inkbird-gateway'.
[8/26/2022, 8:39:33 AM] Warning: skipping plugin found at '/usr/local/lib/node_modules/homebridge-inkbird-wifi-gateway-platform' since we already loaded the same plugin from '/usr/local/lib/node_modules/homebridge-inkbird-gateway'.

Need help working through these,

Thank you

**Comment by tonyburton** [comment]
I have this same issue. This is my first installation of the plugin.

**Comment by mkz212** [comment]
How to solve this?
