### ISSUE TITLE
Plugin not installing

### ISSUE THREAD

**Issue by Gooliga** [richierockskool/homebridge-inkbird-wifi-gateway#8]
While installing following NPM error is produced-
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -2
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2022-07-21T13_00_26_460Z-debug-0.log

Operation failed. Please review log for details.

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**: 
OS - Ubuntu

**Comment by richierockskool** [comment]
"platforms": [
   {
      "platform"       : "HomebridgeInkbirdWifiGateway",
      "plugin_map"      :
      {
         "plugin_name": "homebridge-inkbird-wifi-gateway",
         "index": 0
      },
      "name"            : "Homebridge Inkbird Wifi Gateway Platform",
      "model"           : "IBS-M1S",
      "mac_address"     : "e8:db:84:b6:9c:e6",
      "update_interval" : 600,
      "storage"         : "filesystem",
      "loglevel"        : 3
   }
]

**Comment by richierockskool** [comment]
We are looking for help to resolve this.

**Comment by Gooliga** [comment]
Hi, still same issue - 
1) Added required lines to config file - 
 "platforms": [
        {
            "platform": "HomebridgeInkbirdWifiGateway",
            "plugin_map": {
                "plugin_name": "homebridge-inkbird-wifi-gateway",
                "index": 0
            },
            "name": "Homebridge Inkbird Wifi Gateway Platform",
            "model": "IBS-M1S",
            "mac_address": "e8:db:84:ba:27:33",
            "update_interval": 600,
            "storage": "filesystem",
            "loglevel": 3
        },

2) After updating config file, quick restart on Homebridge
3) Try to install via Homebridge web -> plugins page
Following error is generated - 
USER: homebridge
DIR: /usr
CMD: sudo -E -n npm install -g homebridge-inkbird-wifi-gateway@1.0.2

npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -2
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2022-07-21T19_01_55_466Z-debug-0.log

Operation failed. Please review log for details.

**Comment by richierockskool** [comment]
We have not been able to figure out why Homebridge can not ind the plugin. Stay tuned.

**Comment by RegisCorbet** [comment]
Exact same issue here

**Comment by richierockskool** [comment]
We need someone from GitHub to review and let us know which piece of the puzzle we are missing.

**Comment by RegisCorbet** [comment]
No news? tried to install the plugin once again, and nothing new:
Logs from homebidge:

[1/9/2023, 8:12:34 AM] ====================
[1/9/2023, 8:12:34 AM] ERROR LOADING PLUGIN homebridge-inkbird-wifi-gateway:
[1/9/2023, 8:12:35 AM] Error: Cannot find module '/volume1/homebridge/node_modules/homebridge-inkbird-wifi-gateway/src/index.js'
Require stack:
- /volume1/homebridge/node_modules/homebridge/lib/plugin.js
- /volume1/homebridge/node_modules/homebridge/lib/pluginManager.js
- /volume1/homebridge/node_modules/homebridge/lib/server.js
- /volume1/homebridge/node_modules/homebridge/lib/cli.js
- /volume1/homebridge/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Plugin.load (/volume1/homebridge/node_modules/homebridge/src/plugin.ts:227:93)
    at PluginManager.initializeInstalledPlugins (/volume1/homebridge/node_modules/homebridge/src/pluginManager.ts:141:22)
    at Server.start (/volume1/homebridge/node_modules/homebridge/src/server.ts:173:30)
[1/9/2023, 8:12:35 AM] ====================

**Comment by richierockskool** [comment]
I need another pair of eyes on the coding, I have asked for help, no one is assisting

**Comment by RegisCorbet** [comment]
Too bad, because this plugin would be useful for many people as there is obviously no alternative. Thank you for your answer.

**Comment by cjhdc** [comment]
Install succeeded for me:

npm install -g https://github.com/dwimberger/homebridge-inkbird

**Comment by jlborggreve** [comment]
Not working! Really looking forward to this being solved

**Comment by sebaslag** [comment]
> No news? tried to install the plugin once again, and nothing new: Logs from homebidge:
> 
> [1/9/2023, 8:12:34 AM] ==================== [1/9/2023, 8:12:34 AM] ERROR LOADING PLUGIN homebridge-inkbird-wifi-gateway: [1/9/2023, 8:12:35 AM] Error: Cannot find module '/volume1/homebridge/node_modules/homebridge-inkbird-wifi-gateway/src/index.js' Require stack:
> 
> * /volume1/homebridge/node_modules/homebridge/lib/plugin.js
> * /volume1/homebridge/node_modules/homebridge/lib/pluginManager.js
> * /volume1/homebridge/node_modules/homebridge/lib/server.js
> * /volume1/homebridge/node_modules/homebridge/lib/cli.js
> * /volume1/homebridge/node_modules/homebridge/bin/homebridge
>   at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
>   at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>   at Module.require (node:internal/modules/cjs/loader:1005:19)
>   at require (node:internal/modules/cjs/helpers:102:18)
>   at Plugin.load (/volume1/homebridge/node_modules/homebridge/src/plugin.ts:227:93)
>   at PluginManager.initializeInstalledPlugins (/volume1/homebridge/node_modules/homebridge/src/pluginManager.ts:141:22)
>   at Server.start (/volume1/homebridge/node_modules/homebridge/src/server.ts:173:30)
>   [1/9/2023, 8:12:35 AM] ====================

Same problem here

**Comment by sebaslag** [comment]
Error changed:

npm ERR! code ENOENT
npm ERR! path /usr/lib/node_modules/homebridge-inkbird-wifi-gateway/node_modules/homebridge-inkbird-wifi-gateway
npm ERR! enoent ENOENT: Cannot cd into '/usr/lib/node_modules/homebridge-inkbird-wifi-gateway/node_modules/homebridge-inkbird-wifi-gateway'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by richierockskool** [comment]
We are getting closer to solve this mystery! hang tight!

**Comment by RegisCorbet** [comment]
Really!

**Comment by richierockskool** [comment]
I hope so, we have homebridge looking at it.

It still has the same errors if you install it globally though

**Comment by sebaslag** [comment]
No news?

**Comment by sebaslag** [comment]
I got the same error:
CMD: sudo -E -n npm install -g homebridge-inkbird-wifi-gateway@1.0.7

npm ERR! code ENOENT
npm ERR! path /usr/lib/node_modules/homebridge-inkbird-wifi-gateway/node_modules/homebridge-inkbird-wifi-gateway
npm ERR! enoent ENOENT: Cannot cd into '/usr/lib/node_modules/homebridge-inkbird-wifi-gateway/node_modules/homebridge-inkbird-wifi-gateway'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by RegisCorbet** [comment]
Hi, it looks like you're working hard on the project, but I don't see a new version of the installation after June 18th in the HomeBridge installation console. Is this normal? Thanks your work.
